version: '3.8'

services:
  postgres:
    container_name: postgres-db
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTRES_USER=${TYPEORM_USERNAME}
      - POSTRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTRES_DB=${TYPEORM_DATABASE}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    ports:
      - ${TYPEORM_LOCAL_PORT}:${TYPEORM_PORT}
  
  app:
    container_name: nest-graphql
    build: 
      context: ./
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - ${API_LOCAL_PORT}:${API_PORT}
    environment:
      - API_PORT=${API_PORT}
      - API_LOCAL_PORT=${API_LOCAL_PORT}
      - API_HOST=${API_HOST}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_LOCAL_PORT=${TYPEORM_LOCAL_PORT}
      - TYPEORM_HOST=postgres
